
kind: Cluster
name: kind
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30081
    hostPort: 30081
  - containerPort: 15021
    hostPort: 15021
  - containerPort: 30000
    hostPort: 8000
  extraMounts:
  - hostPath: /prometheus
    containerPath: /prometheus
    propagation: HostToContainer
  - hostPath: /grafana
    containerPath: /grafana
    propagation: HostToContainer
